### ISSUE TITLE
Working with real certificate

### ISSUE THREAD

**Issue by fabianmossberg** [nessla/omnipay-swish#1]
I can't get this to work with a real certificate. It works fine with the test certificate but not with the generated. Any guide on how to generate the real certificates? I followed the one supplied by Swish but no luck.a

**Comment by Jellyfrog** [comment]
Hi
We're about to launch in production and noticed the same thing too, might have a patch for this, testing it tonight

**Comment by fabianmossberg** [comment]
Doesn't seem to have anything to do with your code though, seems to be related to Swish and the certificates. I cant get the command line requests to work either.

The test certificates they give out are pkcs12 while the one you generate is pkcs7 or PEM.

**Comment by Jellyfrog** [comment]
Ok, seems i've been confused with the URL for production, could you please try now? It works for us!

**Comment by fabianmossberg** [comment]
Hey! I just got an answer from Swish. It's my bank who hasn't activated our Swish number properly. When logging in on the internet bank it says that it's activated, and we were told that it was activated, but according to Swish it is not. Called the bank and they looked at it confirming what Swish said. They are activating it properly today and i'll give it a new try then.
